name: lojavirtual
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  lint: ^1.5.3
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.1
  provider: ^5.0.0
  carousel_pro: ^1.0.0
  flutter_staggered_grid_view: ^0.3.4
  transparent_image: ^2.0.0
  alphabet_list_scroll_view: ^2.0.0
  faker: ^1.3.0
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  uuid: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  #assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg